# Generated by Django 4.1.7 on 2023-04-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('player_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('level_id', models.IntegerField()),
                ('gd_version', models.CharField(max_length=5)),
                ('rating', models.CharField(max_length=20)),
                ('is_collab', models.BooleanField()),
                ('duration', models.CharField(max_length=20)),
                ('objects_type', models.Field()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.player')),
            ],
        ),
        migrations.CreateModel(
            name='CollabMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.ManyToManyField(to='levels.player')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
        ),
    ]
